### ISSUE TITLE
Support per-locale GlotPress admins

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Network#23]
Quoting @Mte90 from Slack:

> the big problem is that glotpress doesn't support admin for locales but admin for all the locales and project
> instead wp.org has that because they implemented it and replicate it require a lot of studying of the code because there is no documentation

> or we create a new group with the various capabilities but again the problem to assign a specific locale to an user without developing is very difficult

**Comment by Mte90** [comment]
OK it is time to get work on this!

Looking how worpdress to that:

- They have a table in the db with all the GTE/PTE with roles and permission
- They have a list as class table to easily manage

We can evaluate if we want replicate it or for us is enough to add few fields as usermeta where we assign if they are gte for a locale.
Right now we don't have the infrastructure to implement also new stuff.

With https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-gp-rosetta-roles/inc/class-plugin.php#L70 we can reuse their code and do a minimalistic version.
What do you think @nylen?

**Comment by nylen** [comment]
> We can evaluate if we want replicate it or for us is enough to add few fields as usermeta where we assign if they are gte for a locale.

I think whatever is easiest for you is fine.  I don't see anything here that looks like a big problem, though it does look overcomplicated for what we need to do.

> we can reuse their code and do a minimalistic version.

:+1:

**Comment by Mte90** [comment]
Perfect I will put on my todo list to start to develop something so in the meantime that there is the migration of the server we move on that task.

**Comment by nylen** [comment]
Closing this one, we are most likely moving to https://classicpress.crowdin.com/ for translations.
