### ISSUE TITLE
Link on Get Involved page needs to be updated

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress-Network#27]
On the [Get Involved](https://www.classicpress.net/get-involved/) page, there's a button to "View our dev todo list". This button leads to a [closed milestone](https://github.com/ClassicPress/ClassicPress/milestone/1). It should probably be updated.

**Comment by nylen** [comment]
Fixed, thank you for the report.

I've also given this page a bit more love (added your [idea](https://forums.classicpress.net/t/quick-and-easy-social-promotion-tell-us-which-plugins-and-themes-youre-using-with-classicpress/528) about promoting plugins, added a link to the forums, and a couple of other small updates).
