### ISSUE TITLE
Download page

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Network#33]
Rough mockup

```
Existing WordPress Site?              [Switch to ClassicPress vX]

text here

New ClassicPress Site?                [Download ClassicPress vX]

text here

Need more help?

text here explaining quickly how to get a server and install ClassicPress on it
```

where the **Existing WordPress Site?** and **New ClassicPress Site?** are section headings, and the [Switch] and [Download] are big, clear buttons that link to the zip files

**Comment by EvoRay** [comment]
https://www-new.classicpress.net/get-classicpress/

**Comment by nylen** [comment]
@EvoRay can we change this to be top-to-bottom instead of two columns?  The current layout looks a bit too busy to me, and also this change will allow us to link directly to one section or the other with a `#hash-fragment` (from docs, FAQ answers, etc).

**Comment by EvoRay** [comment]
The problem with a stacked format is that it's a long scroll down to the second (download) option, so it's effectively hidden, and anchor links with only 2 items don't actually work very well.
I guess I could put the sections in a toggle format like the FAQs?

**Comment by EvoRay** [comment]
Switched to toggler. I think it's easier to select and get the info in this format.

**Comment by nylen** [comment]
This looks good, thanks.
