### ISSUE TITLE
Slow loading, especially Font Awesome

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Network#36]
It would be good to move to SVGs (inline or sprite-sheet) for the social icons. Also the site is generally loading a lot of JavaScript for what it's doing (15 files).

**Comment by BlueSkyPhoenix** [comment]
Does anyone have access to the SVG files for all of the icons? I've always used FontAwesome. Icons needed:
Twitter
Facebook
LinkedIn
Github
Slack
Discord
Forums/Discourse

**Comment by nylen** [comment]
This can definitely wait until after we go live, but the files are here:

- https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/brands/twitter.svg
- https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/brands/facebook.svg
- https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/brands/linkedin.svg
- https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/brands/github.svg
- https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/brands/slack.svg
- https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/brands/discord.svg
- https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/brands/discourse.svg

Total size of all of those is 5.7 KB, I think it would be OK to add them to the page load as inline SVGs.  I also wonder if we really see enough activity on LinkedIn and Discord to make including these worth it.

There is also this one for external links, probably hosting it ourselves and loading it in as a `background-image` would be appropriate: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/solid/external-link-alt.svg

**Comment by timbocode** [comment]
A couple of quick wins for the homepage are the two images. I was able to reduce the dashboard image down from 245KB to 74KB and the hands image from 57KB to 17KB without any noticeable reduction in quality. Total saving of over 200KB. The dashboard image is also twice as large (1280px x 719px) as it needs to be.

![get-cp-home](https://user-images.githubusercontent.com/4199514/63967368-2fa82f80-ca95-11e9-93c3-8bce3fd89afa.png)

![hands-vote](https://user-images.githubusercontent.com/4199514/63967369-3040c600-ca95-11e9-9f1d-e8936728a2cc.jpg)

**Comment by nylen** [comment]
@timbocode let's not decrease the resolution of the dashboard image too much, we still want it to look nice and crisp on high-density screens.

**Comment by timbocode** [comment]
No, that's fine. I've replaced the two images with squished versions (84KB and 27KB respectively) so still a saving of 190KB. And I've left the dashboard image at 1280px. To my eyes, there is no difference in quality even when zoomed. The original images are still on the site, just not being used at present. Be interested to see what others think.

**Comment by johnalarcon** [comment]
Agree with the comment about high-density screens. I don't have a retina device to test on, but, probably better to err on the side of caution. If the image is exactly 2x the dimensions it seems it should be, that's probably done precisely for retina support which requires that images are exactly 2x the size of their non-retina counterpart, IIRC.

**Comment by striebwj** [comment]
It is a little blurry on the retina display, but when at default zoom it is okay.

**Comment by timbocode** [comment]
To be honest, I think it's also a little blurry on a standard desktop but I don't think reducing the file size from 245KB to 84KB is "to blame". The original 245KB and the new 84KB files look identical to me. Tested on various devices including a 2@ iPad Mini 4.

If you've got access to admin, try switching between get-cp-home.png (245KB) and get-classicpress.png (84KB) and see what you think. It could just be my eyes..... :)

**Comment by striebwj** [comment]
It is okay for now, we can adjust it after we launch to make sure it isn't blurry :)

**Comment by johnalarcon** [comment]
I just looked at the actual, un-resized image. The problem starts there. The image is probably mid-quality jpg. I'm seeing a lot of artifacts where text is on white, so, even at full-size, it's not real crisp.

**Comment by nylen** [comment]
This is pretty much fixed, with the latest changes from @timbocode to get rid of Font Awesome and load all fonts from the main domain, the loading time has been decreased from roughly 10-12 seconds to 5-6 seconds. There are a few icons still left to re-add to the new icon set (the three icons on the homepage "blocks" section):

![2019-09-04T03 21 29Z](https://user-images.githubusercontent.com/227022/64223670-5c5cac80-cec4-11e9-9d83-a3d8711b9126.png)

This can be done separately, along with further changes to the screenshot. I think I'd probably make a screenshot that shows the classic editor being used to edit a post with several different types of elements. For now though I am closing this and we can follow up with these tasks in separate issues.
