### ISSUE TITLE
Home Page Issues

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress-Network#40]
1. CTAs to switch/download ClassicPress start the download... but, what does the user do next? A small link under each CTA leading to instruction would help. There is a CTA leading to docs below; it's not close enough to serve the purpose.
![image](https://user-images.githubusercontent.com/12477319/61867992-4a332b80-ae8d-11e9-98e9-ebd3f70f8503.png)

2. Improved Security block on homepage, missing comma. It should read, "We are, too."
![image](https://user-images.githubusercontent.com/12477319/61868035-62a34600-ae8d-11e9-9460-54081146edcf.png)

**Comment by nylen** [comment]
(1) will be resolved by #33

(2) I would not put a comma here personally, maybe "So are we." would be better?

**Comment by johnalarcon** [comment]
(1) Noted.

(2) IMO, no.
