### ISSUE TITLE
Roadmap Issues

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress-Network#42]
1. The word "our" is not needed in this link:
![image](https://user-images.githubusercontent.com/12477319/61868340-10aef000-ae8e-11e9-8dd7-e555d50f5a69.png)

2. The word "Our" here is miscapitalized, but, it's awkward; I'd remove the word altogether.
![image](https://user-images.githubusercontent.com/12477319/61868432-376d2680-ae8e-11e9-800e-5aafdb7535ea.png)

3. The phrase "backwards compatible" is incorrect. Correct is "backward compatible".
![image](https://user-images.githubusercontent.com/12477319/61868530-6e433c80-ae8e-11e9-9c80-f4984aad5c10.png)

4. The phrase "plugin / theme authors" should be fully spelled out as "plugin and theme authors"
![image](https://user-images.githubusercontent.com/12477319/61868604-92068280-ae8e-11e9-9070-f6d25317c6a0.png)

5. The term "security-first" doesn't need a hyphen.
![image](https://user-images.githubusercontent.com/12477319/61868713-ddb92c00-ae8e-11e9-86d9-eb0769dc4e5d.png)

6. The phrase "We’ve introduced a well-thought-out versioning scheme based on a modern industry standard" is awkward. It flows better with less words as:
"We’ve introduced a modern industry-standard versioning scheme". Also, this entry lacks a period while the other items in the list do not:
![image](https://user-images.githubusercontent.com/12477319/61868685-ca0dc580-ae8e-11e9-9978-0476fba960bd.png)

7. External link indicators seem outlined but missing; see previous screenshot.

8. Less bloat section: missing comma.
![image](https://user-images.githubusercontent.com/12477319/61868804-0c370700-ae8f-11e9-84b3-36c54425df83.png)
![image](https://user-images.githubusercontent.com/12477319/61868818-13f6ab80-ae8f-11e9-8872-5fe80e71f8c0.png)

9. Headings should follow title-caps format:
![image](https://user-images.githubusercontent.com/12477319/61868867-2ffa4d00-ae8f-11e9-814d-4714f5e79c6d.png)
![image](https://user-images.githubusercontent.com/12477319/61869496-992e9000-ae90-11e9-9bcb-14b414b18d33.png)

10. Missing hyphens? "little-to-no
![image](https://user-images.githubusercontent.com/12477319/61868916-486a6780-ae8f-11e9-8093-09781f9f7612.png)

11. Incorrect wording "included into" should read "included in"
![image](https://user-images.githubusercontent.com/12477319/61869065-9f703c80-ae8f-11e9-964c-fb04c0984fac.png)

12. Inconsistent capitalization; (this and other pages) some say "Version 1" and "Version 2" while others say "version 1" and "version 2" Scan the database and replace one way or the other for consistency.
![image](https://user-images.githubusercontent.com/12477319/61869157-dcd4ca00-ae8f-11e9-845c-5616416aa7e2.png)

13. Misspelling "modernise"
![image](https://user-images.githubusercontent.com/12477319/61869203-f249f400-ae8f-11e9-8cd5-736b888b8445.png)

14. A single sentence is not a paragraph.
![image](https://user-images.githubusercontent.com/12477319/61869282-1d344800-ae90-11e9-942a-f05a4f0eb9c1.png)
![image](https://user-images.githubusercontent.com/12477319/61869297-258c8300-ae90-11e9-8aca-fd07b186cc03.png)

15. Incorrect wording "in service to our mission to create" should be "in service **of** our mission to create"
![image](https://user-images.githubusercontent.com/12477319/61869357-4654d880-ae90-11e9-8e6c-c2a5d927b5f5.png)

16. Awkward wording: "turned on by default" should be "enabled by default"
![image](https://user-images.githubusercontent.com/12477319/61869415-6daba580-ae90-11e9-9d9c-9d49870e7bb5.png)

17. "Through no fault of their own" is not really true; I'd remove it. Also the word "poor" could be replaced with "lower".
![image](https://user-images.githubusercontent.com/12477319/61869574-ca0ec500-ae90-11e9-856c-c98fc67e5b11.png)

18. Punctuation should lie within parentheses, not outside. Not just this page.
![image](https://user-images.githubusercontent.com/12477319/61869684-0e9a6080-ae91-11e9-8171-b9feb8d83935.png)

**Comment by johnalarcon** [comment]
Item 7 above was just also reported in #46

**Comment by nylen** [comment]
I don't agree with every one of the stylistic choices here but this is good feedback, thank you.

**Comment by nylen** [comment]
Also, the slug for the roadmap page should be `roadmap`, not `classicpress-roadmap`.
