### ISSUE TITLE
Join Slack Link

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress-Network#43]
I think we should be using the https://classicpress.net/join-slack/ link. 

I would also like to see the same thing set up for Discord so we don't need to find that link everytime someone asks.

**Comment by nylen** [comment]
Agreed, and this link also needs to be ported over to the new server.

Please use https://www.classicpress.net/join-slack/ (with www) to avoid an extra redirect.

**Comment by nylen** [comment]
This is done, thanks Wade!

**Comment by nylen** [comment]
Actually I guess we still need to use the link on the new site, but it is added (along with `/join-discord/`).

**Comment by striebwj** [comment]
I wasn't sure if the theme was separated out into a different repo so I didn't actually add the links into the theme.

**Comment by striebwj** [comment]
Looks like those aren't hard coded in, we should just be able to change the link.

**Comment by nylen** [comment]
I just fixed the remaining instances of the Join Slack link.
