### ISSUE TITLE
FA external-link-alt not showing

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress-Network#46]
Just shows as a square:
![Screen Shot 2019-07-25 at 7 17 21 AM](https://user-images.githubusercontent.com/14165147/61870561-698d8100-aeac-11e9-9ac6-717befcc1c81.png)

Here is the css:
![Screen Shot 2019-07-25 at 7 19 50 AM](https://user-images.githubusercontent.com/14165147/61870654-9f326a00-aeac-11e9-8603-64f0aac9c338.png)

**Comment by striebwj** [comment]
Added a PR with a fix for this.

**Comment by EvoRay** [comment]
Not finding the PR with the fix. Also curious as to why the issue does not appear for me? Enlighten me?
<img width="381" alt="Screen Shot 2019-07-26 at 1 46 32 PM" src="https://user-images.githubusercontent.com/21056/61977548-fff49c00-afab-11e9-8ee5-b04193459be2.png">

**Comment by striebwj** [comment]
It is in another repo that @nylen is using. 

Not sure why it is working for you. I tried it on Chrome, Firefox, Opera, and Safari. @johnalarcon also had issues with it. 

Here is how I got it to work:
![Screen Shot 2019-07-26 at 3 53 07 PM](https://user-images.githubusercontent.com/14165147/61977817-7cdc4180-afbd-11e9-843b-14d510e9633e.png)

**Comment by EvoRay** [comment]
Is it now fixed for you?
Now it's broken for me (empty box like your earlier screenshot)

**Comment by EvoRay** [comment]
@striebwj I went back to to using FA4 (could not find a way to make it work with FA5), but added a v4 shim. Please let me know if that fixed the issue for you:
https://www-new.classicpress.net/classicpress-roadmap/

**Comment by nylen** [comment]
Still not working for me on Linux.

**Comment by johnalarcon** [comment]
Working for me on this end. Win/FF/Chrome

**Comment by nylen** [comment]
Looking good for me here.

**Comment by nylen** [comment]
Please comment/reopen if this needs any further attention.
