### ISSUE TITLE
Use of !important will make future maintenance more difficult

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Network#47]
As of now:

```
$ grep '!important' wp-content/themes/classicpress-susty-child/style.css | wc -l
36
```

None of these should be necessary:

```
$ grep '!important' wp-content/themes/susty-master/style.css | wc -l
3
```

All 3 instances in the parent theme are related to the `screen-reader-text` class which is a bit of a special case and shouldn't need to be overridden anywhere.

**Comment by timbocode** [comment]
Hoping this is complete. Just need James to confirm.

**Comment by timbocode** [comment]
All but one !important rules removed. Also added page slug to body class to help with individual page styling. Added dropdown indicators to submenus.

**Comment by nylen** [comment]
These changes are live, and the remaining `!important` rule (for `.center { text-align: center !important; }`) makes some sense to leave in place. Thanks again for helping out with this and the other issues you've been working on.
