### ISSUE TITLE
GitHub download links need updating

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Network#50]
Links from https://www-new.classicpress.net/get-classicpress/, probably also appear in other places on the site.

---

The link to download the migration plugin is currently:

> https://api.github.com/repos/ClassicPress/ClassicPress-Migration-Plugin/zipball/1.0.1

but it should be this instead:

> https://github.com/ClassicPress/ClassicPress-Migration-Plugin/releases/download/1.0.1/switch-to-classicpress.zip

See https://github.com/ClassicPress/ClassicPress-Migration-Plugin/releases for details. The existing code that gets a list of GitHub releases is probably not flexible enough to handle this situation yet.

---

The link to download the latest ClassicPress release is currently:

>https://api.github.com/repos/ClassicPress/ClassicPress/zipball/1.0.1+dev

but it should be this instead:

> https://github.com/ClassicPress/ClassicPress-release/archive/1.0.1.zip

(note different URL format, and also `ClassicPress-release` instead of `ClassicPress` repository).

**Comment by EvoRay** [comment]
I don't understand. I thought Omukiguy's Latest Github Release plugin tracked the latest version in a repo. Did the repo change?

**Comment by nylen** [comment]
No, it just doesn't do all it needs to do yet. Also, ClassicPress has two repositories, one for development and one for releases. Using the `ClassicPress/ClassicPress-releases` repository instead of `ClassicPress/ClassicPress` will fix part of this issue, and updating the plugin code will fix the rest.

**Comment by BlueSkyPhoenix** [comment]
Has someone connected w/ Omukiguy to have him update his plugin? Is this all set from that perspective, at least?

**Comment by nylen** [comment]
@bahiirwa see above, https://github.com/bahiirwa/Latest-Github-Release needs an update to its URL logic before we can use it on the new site. I had originally suggested using the `zipball_url` from the API response, but that isn't going to work for us. Here is a refinement:

- if `assets[0]` is set in the API response, use its `browser_download_url` as the release URL
- otherwise, build a URL like `https://github.com/{$user}/{$repo}/archive/{$version}.zip` and use it instead

Also, these links shouldn't have `target="_blank"`.

Are you able to take a look at this sometime? Otherwise I will submit a PR over there.

**Comment by bahiirwa** [comment]
I have looked into this using the documentation. Ref: https://developer.github.com/v3/repos/releases/#list-assets-for-a-release

When I do a dummy run for https://api.github.com/repos/ClassicPress/ClassicPress-release/releases/16076285 which is the latest release for CP; the assets array is empty. This is the same for the ClassicPress/ClassicPress repo.

This is different for the migration plugin however. What is not being done right for the former?

**Comment by bahiirwa** [comment]
I have pushed changes to this effect on [Github](https://github.com/bahiirwa/Latest-Github-Release)

**Comment by nylen** [comment]
Still needs a couple more fixes, we have been chatting about this via DM

**Comment by nylen** [comment]
This is fixed on the site, and I've submitted the changes back to the original plugin: https://github.com/bahiirwa/Latest-Github-Release/pull/1
