### ISSUE TITLE
Add classicpress-latest.zip download

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Network#52]
Split off from https://github.com/ClassicPress/ClassicPress/issues/453

- https://www.classicpress.net/classicpress-latest.zip or https://www.classicpress.net/latest.zip to start
- future options for latest beta, latest nightly, etc?

**Comment by nylen** [comment]
This is done. The following URLs are available now:

- https://www.classicpress.net/latest.json
- https://www.classicpress.net/latest.zip
- https://www.classicpress.net/latest-migration-plugin.json
- https://www.classicpress.net/latest-migration-plugin.zip

**Comment by johnalarcon** [comment]
This is something I can totally use today... thanks!
