### ISSUE TITLE
Latest post title showing on 404 page

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress-Network#53]
The [404 page](https://www-new.classicpress.net/some-random-page) is showing the title of the latest post. My guess is there's a custom query in the 404 template that missed a call to [wp_reset_postdata()](https://codex.wordpress.org/wp_reset_postdata).

![image](https://user-images.githubusercontent.com/12477319/63125609-e6b78d80-bf62-11e9-88c1-0281b8a5d928.png)

**Comment by nylen** [comment]
Thank you @timbocode for fixing this!
