### ISSUE TITLE
Add custom error pages

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Network#6]
In https://github.com/ClassicPress/ClassicPress/issues/20#issuecomment-425661592, @stefanos82 writes:

> https://www.classicpress.net/wp-content/uploads/ and https://www.classicpress.net/wp-includes/ return plain NGINX `403 Forbidden` message.
>
> The website needs custom error messages to reduce valuable information about the stack tech used behind the scenes.

cc: @dsnid3r @striebwj @scottybo

**Comment by dsnid3r** [comment]
Added to my to do list.

**Comment by johnalarcon** [comment]
@dsnid3r, I haven't seen you around in some time; are you still involved with ClassicPress?

**Comment by nylen** [comment]
This is done.

**Comment by nylen** [comment]
Just kidding, the way I did this broke some other things so I've undone it.

**Comment by nylen** [comment]
This should be OK as of several months ago now, at least for the most common cases... please let me know if you see anything else that should be blocked.
