### ISSUE TITLE
Several missing redirects

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress-Network#61]
Looks like a roadmap redirect was missed when building the new site. Recommend scanning the database and replacing with the new URL, as well as setting up a redirect to preserve any previously created external links.

**Old URL**: https://www.classicpress.net/classicpress-roadmap/

**New URL**: https://www.classicpress.net/roadmap/

Reported via the forums.
https://forums.classicpress.net/t/introducing-the-new-classicpress-website/1536/11

**Comment by nylen** [comment]
Thanks for reporting. The URL on the old site was `/roadmap/` also. The `/classicpress-roadmap/` URL was used briefly during the development of the new site, and as you say, it looks like we didn't update all instances in the database. I will do that and add a redirect shortly.

**Comment by johnalarcon** [comment]
Thanks. I'll connect the dots back on the forum afterward.

**Comment by johnalarcon** [comment]
Found a couple more redirects are missing. I have suspicions there are going to be a good handful of these. Advise to review the 404s that are occurring (with Google tools or a plugin) and ensure that every 404 is properly redirected to avoid harming SEO mojo.

https://www.classicpress.net/migrate/
https://www.classicpress.net/faqs/#what-will-be-new-different-in-classicpress-v1

**Comment by nylen** [comment]
The redirects listed in this issue are fixed now.

>I have suspicions there are going to be a good handful of these. Recommend reviewing the 404s that are occurring (with Google tools or a plugin) and ensure that every 404 is properly redirected to avoid harming SEO mojo.

@striebwj @BlueSkyPhoenix can one of you take a look in the Google console and see if there are any other 404s we need to address?

**Comment by striebwj** [comment]
I am not seeing any 404s in the search console.  That being said, I created a custom report in Google Analytics, here are the 404s so far (more will likely show up as people use the site): 

- /classicpress-roadmap/
- /blog/faqconc/how-to-revert-to-wp-498/
- /blog/tag/elementor-sticky/
- /classicpress-roadmap/
- /version/1.0.2
- /blog/classicpress-for-business-professional-organization-websites/
- /faqs/
- /migrate/
- /our-mission/

**Comment by nylen** [comment]
The above redirects are all fixed.

Closing this issue, let me know if anything else comes up here.

**Comment by striebwj** [comment]
@nylen a couple of 404's since:
- [ ] /get-involved/
- [ ] /donate/

**Comment by nylen** [comment]
Thanks Wade, these are added now.

**Comment by striebwj** [comment]
Couple more that I've found:

- [ ] /translating-classicpress/
- [ ] /blog/can-i-use-the-classicpress-beta-on-live-website/
- [ ] /blog/meet-the-community-patrick-klein/
- [ ] /roadmap/%EF%BB%BF (this one threw me when I saw it in GA as just `/roadmap/`

**Comment by nylen** [comment]
https://www.classicpress.net/blog/classicpress-localization/ - This post contains some text that says `(link)` instead of the actual links. Can you track these down when you get a chance?

>/roadmap/%EF%BB%BF

How many times does this appear, any other info such as referrer? It looks like someone created an incorrect URL here, so unless it was us then I'm not sure if this one is worth worrying about.

Other than that, this latest round is fixed.

**Comment by striebwj** [comment]
6 pageviews, but that isn't quite accurate because I posted about it on #random. 

Re the posts using just the word link, I can figure out a way to track those down. For now I will close this issue though.

**Comment by johnalarcon** [comment]
After installing the migration plugin, there's a notice:

![image](https://user-images.githubusercontent.com/12477319/68805870-84c9fb00-0619-11ea-9296-bf8a185d47cc.png)
The first link is to:
https://www.classicpress.net/version/_custom_migration
...which redirects to a 404 on GitHub...
https://github.com/ClassicPress/ClassicPress-release/releases/tag/_custom_migration
