### ISSUE TITLE
Blockquote with only margin doesn't distinguish other paragraphs in a blog post.

### ISSUE THREAD

**Issue by devsrealm** [ClassicPress/ClassicPress-Network#67]
Only defining the blockquote style as a margin doesn't distinguish other paragraphs in a blog post.

**Take for example the below image, can you spot the important section:**

![no blockquote stlye cp theme](https://user-images.githubusercontent.com/37757164/72168425-7441c100-33cd-11ea-81a3-48d00184fa87.png)

**Compared to something like this:**

![blockquote stlye cp theme](https://user-images.githubusercontent.com/37757164/72168509-976c7080-33cd-11ea-85e0-67f40e8047cd.png)

Adding this to the border, did the trick
```
 border-left: 4px solid #057f99;
 padding-left: 1em;
```

What do you think?

**Comment by nylen** [comment]
Thanks, fixed with the following addition and a couple of tweaks for the Discourse comments also:

```
blockquote {
       margin: 0 1.5em .75em;
       border-left: 4px solid #057f99;
       padding-left: 1em;
}
```

We'll be putting these sites and their themes etc in public GitHub repositories again soon. In the meantime, please open more issues if you see anything else :sunglasses::+1:
